feedback_list = {"Fail": ["Don't give up {name}, with hard work and dedication, you can achieve great things!",
                          "Let's work together {name} to improve and reach your goals!",
                          "I know you can do better {name}, let's set some goals and work towards them!",
                          "I believe in you {name}, let's keep trying and never give up!",
                          "You can achieve great things {name}, let's work together to reach your full potential!"],
                 "Insufficient": ["Keep working hard {name}, you can do it!",
                                  "Practice makes perfect {name}, don't give up!",
                                  "I believe in you {name}, keep trying!",
                                  "You have so much potential {name}, let's work on it together!",
                                  "I know you can do better {name}, let's set some goals and work towards them!"],
                 "Barely enough": ["You did a great job {name}, but let's work on pushing yourself a little more!",
                                   "Not bad {name}, but let's aim for excellence!",
                                   "You're on the right track {name}, let's keep working towards your goals!",
                                   "You can do even better {name}, let's set some targets and work towards them!",
                                   "Keep pushing yourself {name}, the sky's the limit!"],
                 "Enough": ["Great job {name}! Keep up the good work!",
                            "Well done {name}! You're doing an excellent job!",
                            "You're doing an amazing job {name}, keep it up!",
                            "You're a superstar {name}, let's aim for the stars!",
                            "You're exceeding expectations {name}, let's aim even higher!"],
                 "Almost good": ["You're doing an incredible job {name}, keep up the good work!",
                                 "You're truly gifted {name}, let's work on reaching your full potential!",
                                 "You're doing an exceptional job {name}, let's aim for greatness!",
                                 "You're an inspiration {name}, let's set some big goals and work towards them!",
                                 "You're truly outstanding {name}, let's keep striving for excellence!"],
                 "Good": ["Fantastic work {name}! Keep up the good work!",
                          "You're doing an excellent job {name}, keep it up!",
                          "Great effort {name}, you're making great progress!",
                          "You're a natural talent {name}, let's work on reaching your full potential!",
                          "You're a shining star {name}, let's aim for the stars!"],
                 "Almost very good": ["You're almost there {name}, Keep up the good work!",
                                      "You're getting closer to perfection {name}, keep working hard!",
                                      "Keep pushing yourself {name}, you're almost there!",
                                      "You're on the verge of greatness {name}, let's work towards it!",
                                      "You're not far from being exceptional {name}, let's reach for excellence!"],
                 "Very good": ["You're doing an amazing job {name}, keep it up!",
                               "You're a real pro {name}, let's aim for the top!",
                               "You're a real asset {name}, let's reach for the stars!",
                               "You're a real talent {name}, let's reach for greatness!",
                               "You're a real inspiration {name}, let's work towards excellence!"],
                 "Excellent": ["You're truly exceptional {name}, keep up the good work!",
                               "You're setting a new standard {name}, let's aim even higher!",
                               "You're a real genius {name}, let's reach for greatness!",
                               "You're a true master {name}, let's aim for the top!",
                               "You're a real legend {name}, let's work towards excellence!"]
                 }
